# Generated by Django 3.2.3 on 2021-05-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('to_be_fetched', '0'), ('to_be_processed', '1'), ('done', '2')], default='to_be_fetched', max_length=20)),
                ('title', models.CharField(default='', max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('raw_data', models.CharField(max_length=10000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fetched_date', models.DateTimeField(blank=True)),
                ('processed_date', models.DateTimeField(blank=True)),
                ('try_count', models.IntegerField(default=0)),
                ('other_stuff', models.CharField(max_length=10000)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(default='Article List', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('phase_1', '0'), ('phase_2', '1'), ('done', '2')], default='phase_1', max_length=20)),
                ('processed_count', models.IntegerField(default=0)),
                ('number_of_articles', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleListToDOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_list_id', models.BigIntegerField()),
                ('doi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('Article', '0'), ('Author', '1'), ('Affiliation', '2'), ('Country', '3'), ('Topic', '4')], default='Article', max_length=50)),
                ('article_list_id', models.BigIntegerField()),
                ('specific_information', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(default='', max_length=100)),
                ('article_list_id', models.BigIntegerField()),
                ('specific_information', models.CharField(max_length=10000)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edge', to='api.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edge', to='api.node')),
            ],
        ),
    ]
