# Generated by Django 3.2.3 on 2021-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210601_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fetched_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='other_stuff',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='processed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='raw_data',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
