# Generated by Django 3.2.3 on 2021-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210601_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubmed_raw_data1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pubmed_raw_data2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
