# Generated by Django 3.2.3 on 2021-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210606_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubmed_raw_data1',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pubmed_raw_data2',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='raw_data',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
