# Generated by Django 3.2.3 on 2021-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_node_object_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('author', '0'), ('article', '1'), ('topic', '2')], default='article', max_length=50),
        ),
    ]
