# Generated by Django 3.2.3 on 2021-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_node_node_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelist',
            name='user',
        ),
        migrations.AddField(
            model_name='articlelist',
            name='userId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
