# Generated by Django 3.2.3 on 2021-06-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_article_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('to_be_fetched', '0'), ('to_be_processed', '1'), ('done', '2'), ('failed', '3')], default='to_be_fetched', max_length=20),
        ),
    ]
