# Generated by Django 3.2.3 on 2021-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_edge_edge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlelist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
