# Generated by Django 3.2.3 on 2021-06-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210616_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
