# Generated by Django 3.2.3 on 2021-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_article_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelisttodoi',
            name='processed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='articlelisttodoi',
            name='status',
            field=models.CharField(choices=[('to_be_fetched', '0'), ('to_be_processed', '1'), ('done', '2'), ('failed', '3')], default='to_be_fetched', max_length=20),
        ),
    ]
